// Builds the main-calculator additions and the embeddable calculator.
//   node heartland-drafts/calculators/build-extras.mjs
// Writes:
//   heartland-drafts/main-calculator-additions.html  sections to paste into /peptide-calculator/
//   heartland-drafts/embed/peptide-calculator-embed.html  standalone file for the iframe embed

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..');
const SITE = 'https://heartlandbiolabs.com';
const EMBED_URL = `${SITE}/tools/peptide-calculator-embed.html`;
const css = readFileSync(join(here, 'calc.css'), 'utf8').trim();
const js = readFileSync(join(here, 'calc.js'), 'utf8').trim();

const num = (n, d) => Number(n.toFixed(d)).toLocaleString('en-US', { maximumFractionDigits: d });
const strip = h => h.replace(/<[^>]+>/g, '');

// ---------- reconstitution chart (targets "peptide reconstitution chart") ----------
const vials = [2, 5, 10, 15, 20, 30, 50];
const vols = [1, 2, 3, 5];
const chartRows = vials.map(mg => `    <tr><th scope="row">${mg} mg</th>${vols.map(ml => {
  const c = mg / ml;
  return `<td>${num(c, 2)} mg/mL<br><span class="rc-hint">${num(c * 10, 1)} mcg/unit</span></td>`;
}).join('')}</tr>`).join('\n');

const embedSnippet = `<iframe src="${EMBED_URL}" title="Peptide reconstitution calculator" width="100%" height="820" style="border:0;max-width:640px" loading="lazy"></iframe>
<p style="font-size:13px">Peptide calculator by <a href="${SITE}/peptide-calculator/">Heartland Bio Labs</a></p>`;

const faq = [
  ['What is a peptide calculator?',
   'A peptide calculator works out the concentration of a reconstituted peptide (mass in the vial divided by the diluent volume added) and turns that into syringe measurements: micrograms per unit on a U-100 syringe and the volume of any chosen aliquot. It is also called a peptide reconstitution calculator, a peptide mixing calculator or a bac water calculator. The math is the same under every name.'],
  ['Is a peptide dosage calculator the same as a reconstitution calculator?',
   'The arithmetic is the same: concentration = mass ÷ volume, then aliquot volume = amount ÷ concentration. "Dosage calculator" is simply what many people search for. This calculator reports concentrations and volumes for laboratory preparation records. It does not recommend any dose, and every product Heartland sells is for research use only.'],
  ['How do I use a peptide calculator with an insulin syringe?',
   'A U-100 insulin-type syringe is marked in units, and 100 units equals 1 mL, so 1 unit is 0.01 mL. Enter the vial mass and diluent volume to get the concentration. The calculator then shows how many micrograms each unit contains and how many units a chosen aliquot fills. Units are a volume, not an amount of peptide.'],
  ['How much bacteriostatic water do I need to reconstitute a peptide?',
   'There is no fixed amount. The volume sets the concentration. 1–3 mL is typical for standard 3 mL vials; more water makes each aliquot larger and easier to measure, less water concentrates it. The reconstitution chart on this page shows the concentration for common vial sizes at 1, 2, 3 and 5 mL.'],
  ['Can I put this peptide calculator on my own website?',
   'Yes. Copy the embed code in the "Embed this calculator" section and paste it into any page that accepts HTML. It\'s free and needs no sign-up. Please keep the credit line under the calculator.']
];

const additions = `<!--
  Heartland Bio Labs: additions to the EXISTING /peptide-calculator/ page.
  GENERATED by heartland-drafts/calculators/build-extras.mjs.
  Paste each numbered section where its comment says. Keep the existing content. These are additions.

  Suggested SEO title (≤60): Peptide Calculator: Free Reconstitution & Bac Water Math
  Suggested meta (≤155): Free peptide calculator for reconstitution. Enter vial mg and bac water mL to get mg/mL, mcg per syringe unit and aliquot volume. Chart, formulas and FAQ included.
  Variants this covers: peptide calculator (201k), peptide reconstitution calculator (9.9k), peptide dosage calculator (8.1k, KD 21),
    peptide calc (4.4k), reconstitution calculator (3.6k), peptides calculator (2.9k, KD 9), peptide dose calculator (2.4k),
    peptide reconstitution chart (1k), peptide mixing calculator (880), bac water calculator (390), bacteriostatic water calculator (210).
-->

<!-- ===== 1. Directly UNDER the calculator panel ===== -->
<section class="hbl-rc" aria-labelledby="cc-h">
  <h2 id="cc-h">Compound calculators</h2>
  <p>Pre-filled for each compound's catalog vial sizes, with their own worked tables and FAQs:</p>
  <ul>
    <li><a href="${SITE}/peptide-calculator/semaglutide/">Semaglutide reconstitution calculator</a> (2, 5, 10 mg)</li>
    <li><a href="${SITE}/peptide-calculator/bpc-157/">BPC-157 calculator</a> (5, 10 mg)</li>
  </ul>
</section>

<!-- ===== 2. After the "Choosing the diluent volume" section ===== -->
<section class="hbl-rc" aria-labelledby="chart-h">
  <h2 id="chart-h">Peptide reconstitution chart</h2>
  <p>Concentration and micrograms per U-100 unit for common vial sizes and bacteriostatic water volumes. Each cell is mass ÷ volume. The per-unit figure is the concentration × 10.</p>
  <div class="rc-scroll">
  <table class="rc-table">
    <thead><tr><th scope="col">Vial</th>${vols.map(v => `<th scope="col">${v} mL</th>`).join('')}</tr></thead>
    <tbody>
${chartRows}
    </tbody>
  </table>
  </div>
  <p class="rc-hint">Arithmetic only. No preparation or dose is recommended. Volumes above about 3 mL need a vial larger than the standard 3 mL vial.</p>
</section>

<!-- ===== 3. After the chart ===== -->
<section class="hbl-rc" aria-labelledby="names-h">
  <h2 id="names-h">Reconstitution calculator, mixing calculator, dosage calculator: one formula</h2>
  <p>People search for this tool under many names: <strong>peptide reconstitution calculator</strong>, <strong>peptide mixing calculator</strong>, <strong>bac water calculator</strong>, <strong>peptide dosage calculator</strong> or just <strong>peptide calc</strong>. They all come down to two lines:</p>
  <ol>
    <li><strong>Concentration (mg/mL) = peptide mass in the vial (mg) ÷ bacteriostatic water added (mL)</strong></li>
    <li><strong>Aliquot volume (mL) = amount wanted (mg) ÷ concentration</strong>. On a U-100 syringe, units = mL × 100.</li>
  </ol>
  <p>Example: a 10 mg vial with 2 mL is 5 mg/mL. An aliquot of 300 mcg (0.3 mg) is 0.06 mL, or 6 units. The calculator above does both steps and warns when an aliquot is too small to measure accurately.</p>
  <h3>Bac water calculator: how much bacteriostatic water to add</h3>
  <p>No volume is universally "right". Choose the volume that turns your aliquots into sizes you can measure accurately, usually a few units or more on a U-100 syringe. If an aliquot comes out under 2 units, add more water. For the diluent itself, see <a href="${SITE}/blog/bac-water-for-peptides/">bacteriostatic water for peptides</a>. For the full procedure, see <a href="${SITE}/how-to-reconstitute-peptides/">how to reconstitute peptides</a>.</p>
</section>

<!-- ===== 4. Before the FAQ ===== -->
<section class="hbl-rc" id="embed" aria-labelledby="embed-h">
  <h2 id="embed-h">Embed this calculator</h2>
  <p>Run a forum, research wiki, Discord resource page or blog? You can put this peptide calculator on your own site for free. Copy the code below and paste it into any page that accepts HTML. Please keep the credit line.</p>
  <textarea id="hbl-embed-code" readonly rows="5" style="width:100%;font-family:monospace;font-size:13px;padding:.6em;border:1px solid #d9dee5;border-radius:8px">${embedSnippet.replace(/&/g, '&amp;').replace(/</g, '&lt;')}</textarea>
  <p><button type="button" id="hbl-embed-copy" style="font:inherit;padding:.5em 1em;border-radius:8px;border:1px solid #1f5f8b;background:#1f5f8b;color:#fff;cursor:pointer">Copy embed code</button></p>
  <script>
  (function(){var b=document.getElementById('hbl-embed-copy'),t=document.getElementById('hbl-embed-code');if(!b||!t)return;
  b.addEventListener('click',function(){t.select();var ok=false;try{navigator.clipboard.writeText(t.value);ok=true;}catch(e){try{ok=document.execCommand('copy');}catch(e2){}}b.textContent=ok?'Copied':'Select the code and copy it';setTimeout(function(){b.textContent='Copy embed code';},2000);});})();
  </script>
</section>

<!-- ===== 5. Append to the existing FAQ (same markup style as the other FAQ items) ===== -->
${faq.map(([q, a]) => `<details>\n  <summary>${q}</summary>\n  <p>${a}</p>\n</details>`).join('\n')}

<!-- ===== 6. FAQ schema =====
  If the theme or SEO plugin already outputs FAQPage schema for this page, add these five
  Question objects to it. Otherwise paste this block once, anywhere on the page. Never have
  two FAQPage blocks on one page. -->
<script type="application/ld+json">
${JSON.stringify({ '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: strip(a) } })) }, null, 2)}
</script>

<!-- ===== 7. Styles (paste once, only if the sections above look unstyled) ===== -->
<style>
${css}
.hbl-rc .rc-table td .rc-hint{display:inline}
</style>
`;
writeFileSync(join(out, 'main-calculator-additions.html'), additions);

// ---------- embeddable standalone calculator ----------
const embed = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Peptide Reconstitution Calculator | Heartland Bio Labs</title>
<meta name="robots" content="noindex,follow">
<link rel="canonical" href="${SITE}/peptide-calculator/">
<style>
body{margin:0;padding:12px;font-family:system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;background:#fff}
${css}
.hbl-rc .rc-panel{margin:0}
.hbl-rc .rc-credit{font-size:12px;color:var(--rc-muted);margin:.8em 0 0}
</style>
</head>
<body>
<div class="hbl-rc">
<section id="rc-calc" class="rc-panel" aria-labelledby="rc-calc-h">
  <h2 id="rc-calc-h" style="margin:0 0 .8em;font-size:1.2em">Peptide reconstitution calculator</h2>
  <div class="rc-field">
    <label for="rc-mg">Peptide in vial (mg)</label>
    <div class="rc-chips" data-for="rc-mg">
${[2, 5, 10, 15, 20, 30, 50].map(v => `      <button type="button" data-v="${v}">${v}</button>`).join('\n')}
    </div>
    <input id="rc-mg" type="number" min="0.1" step="0.1" value="5" inputmode="decimal">
  </div>
  <div class="rc-field">
    <label for="rc-ml">Bacteriostatic water added (mL)</label>
    <div class="rc-chips" data-for="rc-ml">
${[1, 2, 3, 5].map(v => `      <button type="button" data-v="${v}">${v}</button>`).join('\n')}
    </div>
    <input id="rc-ml" type="number" min="0.1" step="0.1" value="2" inputmode="decimal">
  </div>
  <div class="rc-field">
    <label for="rc-al">Amount per aliquot (mcg), optional</label>
    <input id="rc-al" type="number" min="0" step="1" placeholder="e.g. 250" inputmode="decimal">
  </div>
  <div class="rc-out" aria-live="polite">
    <div class="rc-stat"><b id="rc-o-conc">2.5 mg/mL</b><span>Concentration</span></div>
    <div class="rc-stat"><b id="rc-o-unit">25 mcg</b><span>per U-100 unit (0.01 mL)</span></div>
    <div class="rc-stat"><b id="rc-o-vol">—</b><span>Aliquot volume</span></div>
    <div class="rc-stat"><b id="rc-o-n">—</b><span>Aliquots per vial</span></div>
  </div>
  <p id="rc-w-small" class="rc-warn">Under 2 units (0.02 mL): too small to measure accurately. More diluent makes the same aliquot a larger volume.</p>
  <p id="rc-w-big" class="rc-warn">A standard 3 mL vial holds about 3 mL of diluent.</p>
  <p id="rc-w-over" class="rc-warn">Larger than a 1 mL (100-unit) syringe.</p>
  <p class="rc-credit">Concentration arithmetic for research use only. No dosage guidance. <a href="${SITE}/peptide-calculator/" target="_blank" rel="noopener">Full calculator, chart and guide by Heartland Bio Labs</a></p>
</section>
</div>
<script>
${js}
</script>
</body>
</html>
`;
mkdirSync(join(out, 'embed'), { recursive: true });
writeFileSync(join(out, 'embed', 'peptide-calculator-embed.html'), embed);
console.log('wrote main-calculator-additions.html and embed/peptide-calculator-embed.html');
